### ISSUE TITLE
Detalhes - Opção de 'details/toggle tracking'

### ISSUE THREAD

**Issue by rascaraficci** [agrotracking/gui#34]
No mapa da página de detalhes, quando clica no dispositivo ele dá a opção de 'details' e 'toggle tracking'. A opção de 'details' não faz sentido e a opção de 'toggle tracking' não está funcionando.

![image](https://user-images.githubusercontent.com/31006659/31889960-4dddc9c0-b7e0-11e7-9e27-e6c2d52cc6a6.png)

**Comment by mmagr** [comment]
Context menu was removed entirely by #62.
