### ISSUE TITLE
Lista - Sidebar some quando o filtro não retorna nenhum dispositivo 

### ISSUE THREAD

**Issue by luisfelipefurlan** [agrotracking/gui#37]
Na visão por card, quando realizado o filtro dos dispositivos de modo que não retorne nenhum dispositivo, o sidebar some.

![image](https://user-images.githubusercontent.com/32846891/31891377-fdbfb5ac-b7e4-11e7-82bc-853743a1b822.png)

**Comment by mmagr** [comment]
Fixed by ac0b324.
