### ISSUE TITLE
Mapa - quando a visibilidade de um dispositivo é alterada, o zoom e a posição do mapa são alterados

### ISSUE THREAD

**Issue by luisfelipefurlan** [agrotracking/gui#39]
![image](https://user-images.githubusercontent.com/32846891/31892209-358dd246-b7e7-11e7-9af3-74be214b030e.png)

![image](https://user-images.githubusercontent.com/32846891/31892221-3f2bc45c-b7e7-11e7-9c74-2a008dbcb3af.png)

**Comment by mmagr** [comment]
Isso também afeta a visualização dos dados em real time.
