### ISSUE TITLE
Detalhes de Device -Opções de tracking e de detalhes disponíveis na tela de detalhes

### ISSUE THREAD

**Issue by lmariote** [agrotracking/gui#57]
Na apresentação de detalhes de um Device, ao clicar no ícone do device no mapa, aparecem as opções de tracking e detalhes, porém elas não fazem nada quando selecionadas
![device detail - incoherent options](https://user-images.githubusercontent.com/32078419/31963806-b7f019d4-b8e0-11e7-9066-86287d0ce0b9.png)

**Comment by mmagr** [comment]
Duplicata de #34.

**Comment by mmagr** [comment]
Context menu was removed entirely by #62.
